-- CREATE TABLE weather_db
-- (
--     id         BIGSERIAL PRIMARY KEY,
--     name       VARCHAR(255) NOT NULL,
--     country    VARCHAR(255) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
